const changeData = async (data) => {
  data.map((item) => {
    const {
      name,
      nip,
      username,
      password,
      email,
      role,
      regional,
      Datum: {
        tgl_lahir,
        no_ktp,
        no_bpjs,
        nama_bank,
        no_rekening,
        satuan_kerja,
        cabang,
        golongan_pangkat,
        no_telp,
        alamat,
        kelurahan,
        kecamatan,
        kota,
        kodepos,
        provinsi,
        nama_pasangan,
        tgl_lahir_pasangan,
        no_telp_pasangan,
        no_ktp_pasangan,
        no_bpjs_pasangan,
        nama_bank_pasangan,
        no_rekening_pasangan,
        nama_anak,
        tgl_lahir_anak,
        no_tlp_anak,
        no_ktp_anak,
        no_bpjs_anak,
        nama_bank_anak,
        no_rekening_anak,
        id,
        userId,
      },
    } = item;
    return {
      name,
      nip,
      username,
      password,
      email,
      role,
      regional,
      id,
      tgl_lahir,
      no_ktp,
      no_bpjs,
      nama_bank,
      no_rekening,
      satuan_kerja,
      cabang,
      golongan_pangkat,
      no_telp,
      alamat,
      kelurahan,
      kecamatan,
      kota,
      kodepos,
      provinsi,
      nama_pasangan,
      tgl_lahir_pasangan,
      no_telp_pasangan,
      no_ktp_pasangan,
      no_bpjs_pasangan,
      nama_bank_pasangan,
      no_rekening_pasangan,
      nama_anak,
      tgl_lahir_anak,
      no_tlp_anak,
      no_ktp_anak,
      no_bpjs_anak,
      nama_bank_anak,
      no_rekening_anak,
      userId,
    };
  });
};

module.exports = changeData;
